### ISSUE TITLE
[BUG] WhatsApp Bridge can't be started without --no-update

### ISSUE THREAD

**Issue by w-marco** [beeper/bridge-manager#46]
When trying to start the WhatsApp Bridge (at least inside Docker, but probably also with the binary directly), it will refuse to start with the following error code:

```
Finding latest version of [cyan]mautrix-whatsapp[reset] from [cyan]mau.dev[reset]
failed to find URL for job "build amd64" on branch main of mautrix/whatsapp
```

I checked the mautrix-whatsapp docs, and they have a link there to download artifacts that corresponds with what the bridge startup tries to do (https://docs.mau.fi/bridges/go/setup.html?bridge=whatsapp, Option 1.1), and it throws a 404.

As a workaround I downloaded the binary from GitHub, put it into the /data/binary folder and ran the Bridge with --no-update, and that worked.

**Comment by rhinot** [comment]
For those who are using docker compose, and since it took someone else helping me to figure it out, the --no-update param goes before the bridge name in the compose file.

So for [my compose file](https://github.com/rhinot/beeper-bridges/blob/main/docker-compose.yml), it would be:
`BRIDGE_NAME=—no-update sh-whatsapp`

Once I did that, I didn't need to download the binary from GitHub. I could just use the binary in the docker image at ghcr.io/beeper/bridge-manager.

**Comment by MinecraftFuns** [comment]
Here is a potential improvement: add a new configuration option in [run.go](https://github.com/beeper/bridge-manager/blob/87cca18e1d4ea6050e5b2ee64dfeb43d2281f906/cmd/bbctl/run.go#L26) that attempts to update the bridge, and if the update fails, it simply launches the old bridge. This should be the default behavior.

If you check the code that downloads and runs the bridge [here](https://github.com/beeper/bridge-manager/blob/87cca18e1d4ea6050e5b2ee64dfeb43d2281f906/cmd/bbctl/run.go#L354), you will find that bbctl refuses to launch the bridge if the update fails, which is not desirable behavior.

**Comment by dvcrn** [comment]
I feel it would be better if https://github.com/mautrix/whatsapp can also generate artifacts for amd64, not just arm64. Pretty sure that was the case in the past because I was able to run it just fine on my amd64 machine 

Should be trivial with buildx. Command I used to build a amd64 container for my server: 

```
docker buildx build --platform linux/amd64,linux/arm64
```

**Comment by na-ji** [comment]
> I feel it would be better if [mautrix/whatsapp](https://github.com/mautrix/whatsapp) can also generate artifacts for amd64, not just arm64. Pretty sure that was the case in the past because I was able to run it just fine on my amd64 machine
> 
> Should be trivial with buildx. Command I used to build a amd64 container for my server:
> 
> ```
> docker buildx build --platform linux/amd64,linux/arm64
> ```

It's not an issue of missing amd64 builds, it's because all the artifacts URLs have moved. Even the arm64 will return a 404 error message now.
